extends Node

var lang = "es"

var texts = {
	"es":{
	"df_enemy":"Te atacará si te mueves o realizas una acción.",
	"df_trap":"Se activa si atraviesas la habitación.",
	"df_block":"Destruyelo para poder pasar por aqui.",
	"df_door":"No puedes pasar por aquí hasta que abras el cerrojo.",
	"df_stairs":"Esta escalera lleva al siguiente nivel.",
	"df_fountain":"Esta fuente sanará hasta 2HP a quien beba de ella.",
	"df_chest":"Si logras abrirlo puedes obtener nuevos items.",
	
	"df_name_goblin":"Goblin",
	"df_name_rat":"Rata Gig.",
	"df_name_bat":"Murcielago",
	"df_name_gorok":"Gorok",
	"df_name_trap":"Trampa",
	"df_name_door":"Puerta",
	"df_name_debris":"Escombros",
	"df_name_wchest":"Cofre",
	"df_name_chest":"Cofre",
	"df_name_stairs":"Escalera",
	"df_name_fountain":"Fuente",
	
	"ac_name_attack":"atacar",
	"ac_attack":"Causa entre 0 y 2 de daño, cada @SW añade un golpe extra.",
	"ac_name_clear":"limpiar",
	"ac_clear":"Limpia entre 0 y 2, cada @SW y cada @HN añade un intento extra.",
	"ac_name_dissarm":"desarmar",
	"ac_dissarm":"Cada @HN y cada @EY mejora la posibilidad de éxito.",
	"ac_name_unlock":"abrir",
	"ac_unlock":"Completa los requisitos según los atributos actuales del personaje.",
	"ac_name_force":"forzar",
	"ac_force":"20% de destruir un requisito aleatorio, esté o no resuelto.",
	"ac_name_recover":"sanar",
	"ac_recover":"Curas tus puntos de vida (HP). Puede agotarse.",
	"ac_name_descend":"bajar",
	"ac_descend":"Necesitas la llave de este nivel y reunir a todos tus personajes aquí para poder descender.",


	"it_reload":"se recupera por nivel",
	"it_reload_not":"se destruye al gastarse",
	"it_old_dage_name":"DAGA VIEJA",
	"it_old_dage_desc":"Si no tiene ninguna @SW, ganas una @SW",
	"it_best_heart_name":"CORAZON DE BESTIA",
	"it_best_heart_desc":"Si tienes @SW@SW, te curas +2HP",
	"it_travel_boots_name":"BOTAS DE VIAJERO",
	"it_travel_boots_desc":"Si tienes @BT@BT, recuperas tu accion, recuperas todo tu movimiento, pero pierdes una @BT",
	"it_picklock_name":"Ganzuas",
	"it_picklock_desc":"Pierdes @EY pero ganas @HN@HN",
	"it_thief_knife_name":"Daga de ladron",
	"it_thief_knife_desc":"Pierdes @BT@HN y ganas @SW@SW",
	"it_healing_stuff_name":"Baston curativo",
	"it_healing_stuff_desc":"Pierdes @EY y recuperas +1HP",
	"it_battle_axe_name":"Hacha de batalla",
	"it_battle_axe_desc":"Si tienes @SW ganas un @SW extra",
	"it_heal_potion_name":"Pocion curativa",
	"it_heal_potion_desc":"Cura +1HP",
	"it_mind_potion_name":"Pocion de astucia",
	"it_mind_potion_desc":"Si tienes @EY ganas un @EY extra",
	

	"tuto_start":"Bienvenido a tu primer mazmorra!\nTe enseñaré lo básico para que puedas jugar..",
	"tuto_pjui":"En la parte inferior estan las fichas de tus personajes, allí verás sus atributos, vida y movimiento.",
	"tuto_dices":"Al comenzar cada turno, se arrojarán los dados de atributos de tus personajes, estos dados te dan ventaja en distintas acciónes.",
	
	"attr_SW":"@SW ESPADA: Fuerza, infliges mayor daño al atacar.",
	"attr_BT":"@BT BOTA: Agilidad, avanzas mas casillas que el resto y te da +10% chances de evadir daño.",
	"attr_HN":"@HN MANO: Maña, mayor facilidad para abrir cerrojos o desactivar trampas.",
	"attr_EY":"@EY OJO: Astucia, mayor facilidad para abrir cerrojos o desactivar trampas, tambien te da +25% chances de encontrar elementos ocultos.",

	"hint_key":"Necesitas encontrar la llave de este nivel, cuando la tengas podras bajar por la escalera al siguiente.",
	"hint_torch":"Cuando tu antorcha se termine, todos tus personajes reciben daño en cada turno.",
	"hint_hp":"HP: Son los puntos de golpe que resiste este desafío.",
	"hint_dif":"DIFICULTAD: Es el nivel de dificultad del desafío, generalmente se ve modificado por los atributos del personaje que interactua.",
	"hint_dm":"DAÑO: Es el daño que puede infligirte este desafío.",
	"hint_test":"TIRADA DE AZAR: Al interactuar se elige aleatoriamente una casilla de azar, si es [color=#FFFFAA]verde[/color], tienes exito, si es [color=#FF9999]rojo[/color] habras fallado.",
	"hint_reqs":"REQUISITOS: Debes completarlos utilizando los atributos de tus personajes para resolver este desafio.",
	"hint_reload_item":"RECARGABLE: Recuperas los usos de este item o habilidad al pasar al siguiente nivel.",
	"hint_items":"INVENTARIO: Los objetos son compartidos, cualquier personaje puede utilizarlos si cumple con su requisito.",
	"hint_show_tuto":"Mostrar tutorial.",

	"dice_neutral":"DADO NEUTRAL",
	"dice_fight":"DADO DE COMBATE",
	"dice_mind":"DADO DE ASTUCIA",
	"dice_agility":"DADO DE DESTREZA",
	"dice_custom":"DADO COMBINADO",
	
	"tx_hp":"HP: Indica la vitalidad del personaje, cuantos puntos de golpe puede resistir antes de morir.",
	"tx_mv":"MV: Indica cuantos movimientos puede realizar el personaje en cada turno.",
	"tx_back":"Volver",
	"tx_play":"Jugar",
	"tx_goto_dungeon":"Bajar al\nDungeon",
	"tx_chose_heroes":"Elige a tres aventureros para bajar al dungeon!",
	
	"tuto_welcome":"[center][color=#f6ff88]BIENVENIDO[/color]\nTu grupo de aventureros ha descendido al primer nivel de este dungeon, debes explorarlo para encontrar la llave y poder bajar al siguiente nivel.",
	"tuto_pjs":"[center][color=#f6ff88]PERSONAJES Y MOVIMIENTO[/color]\nEn la parte inferior estan las fichas de tus personajes, puedes clickearlas o presionar [Q] para seleccionarlos y utilizar [W][A][S][D] para moverte por el dungeon.",
	"tuto_attr":"[center][color=#f6ff88]ATRIBUTOS[/color]\nAl inicio de cada turno tus personajes arrojan sus dados de atributos, dependiendo de los resultados obtendran ventaja para realizar unas u otras acciones.",
	"tuto_defiances":"[center][color=#f6ff88]DESAFIOS Y ACCIONES[/color]\nEncontraras diferentes desafios al explorar, como enemigos, escombros o trampas. Cada uno permite realizar diferentes acciones modificadas por los atributos de tus personajes.",
	"tuto_torch":"[center][color=#f6ff88]ANTORCHAS[/color]\nLas antorchas son la unica forma de mantenerte a salvo, cada turno se reducira su numero, si llega a cero todos tus personajes recibiran daño en cada turno, asegurate de que eso no suceda!",
	"tuto_end":"[center][color=#f6ff88]OBJETIVO[/color]\nEn el cuarto piso esta Gorok el troll, debes vencerlo para superar esta mision, buena suerte a tus aventureros!",

	"tx_skip_tutorial":"SALTAR TUTORIAL",
	"tx_close_tutorial":"CERRAR TUTORIAL",
	"tx_inventory": "INVENTARIO",
	"tx_evade": "ESQUIVA!",
	"tx_need_key": "NESECITAS LA LLAVE DE ESTE NIVEL",
	"tx_need_party": "DEBES REUNIR A TODOS AQUI PARA BAJAR",
	"tx_level": "Nivel",
	"tx_end_turn": "FIN\nTURNO",
	"tx_touch_again":"Toca de nuevo para activar",
	"tx_exhausted":"AGOTADO!",
	"tx_full_hp": "MAXIMO HP!",
	
	"popup_win":"[center][color=#f6ff88]VICTORIA[/color]\nHas vencido a Gorok el troll y liberaste su guarida de todo peligro.\n\nEsperamos que lo hayas disfrutado!",
	"popup_lose":"[center][color=#f6ff88]DERROTA[/color]\nTodos tus aventureros han caido, ya no saldran de este calabozo.\n\nVuelve a intentarlo!",
	},
	"en":{
	"df_enemy": "It will attack you if you move or take an action.",
	"df_trap": "Activates when you cross the room.",
	"df_block": "Destroy it to pass through here.",
	"df_door": "You can't pass through until you unlock it.",
	"df_stairs": "These stairs lead to the next level.",
	"df_fountain": "This fountain will heal up to 2HP if you drink from it.",
	"df_chest": "If you manage to open it, you can get new items.",

	"df_name_goblin": "Goblin",
	"df_name_rat": "Giant Rat",
	"df_name_bat": "Bat",
	"df_name_gorok": "Gorok",
	"df_name_trap": "Trap",
	"df_name_door": "Door",
	"df_name_debris": "Debris",
	"df_name_wchest": "Chest",
	"df_name_chest": "Chest",
	"df_name_stairs": "Stairs",
	"df_name_fountain": "Fountain",

	"ac_name_attack": "attack",
	"ac_attack": "Deals 0 to 2 damage, each @SW adds an extra hit.",
	"ac_name_clear": "clear",
	"ac_clear": "Cleans 0 to 2, each @SW and each @HN adds an extra attempt.",
	"ac_name_dissarm": "disarm",
	"ac_dissarm": "Each @HN and each @EY improves the chance of success.",
	"ac_name_unlock": "unlock",
	"ac_unlock": "Meets the requirements based on the character's current attributes.",
	"ac_name_force": "force",
	"ac_force": "20% chance to destroy a random requirement, whether solved or not.",
	"ac_name_recover": "heal",
	"ac_recover": "Heals your hit points (HP). Might run out.",
	"ac_name_descend": "descend",
	"ac_descend": "You need the key for this level and all your characters gathered here to go down.",

	"it_reload": "recovers each level",
	"it_reload_not": "is destroyed after use",
	"it_old_dage_name": "OLD DAGGER",
	"it_old_dage_desc": "If you have no @SW, gain one @SW",
	"it_best_heart_name": "BEAST HEART",
	"it_best_heart_desc": "If you have @SW@SW, heal +2HP",
	"it_travel_boots_name": "TRAVELER BOOTS",
	"it_travel_boots_desc": "If you have @BT@BT, regain your action, regain all your movement, but lose one @BT",
	"it_picklock_name": "Lockpicks",
	"it_picklock_desc": "Lose @EY but gain @HN@HN",
	"it_thief_knife_name": "Thief Dagger",
	"it_thief_knife_desc": "Lose @BT@HN and gain @SW@SW",
	"it_healing_stuff_name": "Healing Staff",
	"it_healing_stuff_desc": "Lose @EY and heal +1HP",
	"it_battle_axe_name": "Battle Axe",
	"it_battle_axe_desc": "If you have @SW gain one extra @SW",
	"it_heal_potion_name": "Healing Potion",
	"it_heal_potion_desc": "Heals +1HP",
	"it_mind_potion_name": "Cunning Potion",
	"it_mind_potion_desc": "If you have @EY gain one extra @EY",

	"tuto_start": "Welcome to your first dungeon!\nI'll teach you the basics so you can play.",
	"tuto_pjui": "At the bottom are your character cards, where you'll see their attributes, health, and movement.",
	"tuto_dices": "At the start of each turn, your characters will roll their attribute dice, which give you advantages in different actions.",

	"attr_SW": "@SW SWORD: Strength, deals more damage when attacking.",
	"attr_BT": "@BT BOOT: Agility, move more tiles and +10% chance to dodge damage.",
	"attr_HN": "@HN HAND: Skill, better at unlocking or disarming traps.",
	"attr_EY": "@EY EYE: Cunning, better at unlocking or disarming traps, also +25% chance to find hidden items.",

	"hint_key": "You need to find this level’s key. Once you have it, you can go down the stairs to the next one.",
	"hint_torch": "When your torch runs out, all your characters will take damage each turn.",
	"hint_hp": "HP: The amount of hit points this challenge can take.",
	"hint_dif": "DIFFICULTY: Challenge level, usually modified by the interacting character’s attributes.",
	"hint_dm": "DAMAGE: How much damage this challenge can inflict.",
	"hint_test": "LUCK ROLL: When interacting, a random slot is chosen. If it's [color=#FFFFAA]green[/color], you succeed. If it's [color=#FF9999]red[/color], you fail.",
	"hint_reqs": "REQUIREMENTS: Use your character’s attributes to complete them and overcome the challenge.",
	"hint_reload_item": "RECHARGEABLE: Item or skill use is recovered when going to the next level.",
	"hint_items": "INVENTORY: Items are shared. Any character can use them if they meet the requirements.",
	"hint_show_tuto": "Show tutorial.",

	"dice_neutral": "NEUTRAL DICE",
	"dice_fight": "DICE OF FIGHT",
	"dice_mind": "DICE OF MIND",
	"dice_agility": "DICE OF AGILITY",
	"dice_custom": "CUSTOM DICE",

	"tx_hp": "HP: Shows character vitality, how much damage they can take before dying.",
	"tx_mv": "MV: Shows how many moves the character can make each turn.",
	"tx_back": "Back",
	"tx_play": "Play",
	"tx_goto_dungeon": "Enter the\nDungeon",
	"tx_chose_heroes": "Pick three adventurers to enter the dungeon!",
	"tx_exhausted": "EXHAUSTED!",
	"tx_full_hp": "FULL HP!",

	"tuto_welcome": "[center][color=#f6ff88]WELCOME[/color]\nYour group of adventurers has entered the first dungeon level. Explore it to find the key and descend to the next floor.",
	"tuto_pjs": "[center][color=#f6ff88]CHARACTERS & MOVEMENT[/color]\nAt the bottom are your character cards. Click or press [Q] to select, and use [W][A][S][D] to move around the dungeon.",
	"tuto_attr": "[center][color=#f6ff88]ATTRIBUTES[/color]\nAt the start of each turn, your characters roll their attribute dice. The results grant advantages for various actions.",
	"tuto_defiances": "[center][color=#f6ff88]CHALLENGES & ACTIONS[/color]\nYou’ll encounter different challenges while exploring, like enemies, debris, or traps. Each offers actions influenced by your characters’ attributes.",
	"tuto_torch": "[center][color=#f6ff88]TORCHES[/color]\nTorches are your only safety. Each turn one burns out. If none are left, all your characters will take damage each turn. Don't let that happen!",
	"tuto_end": "[center][color=#f6ff88]OBJECTIVE[/color]\nOn the fourth floor is Gorok the troll. Defeat him to complete this mission. Good luck, adventurers!",

	"tx_skip_tutorial": "SKIP TUTORIAL",
	"tx_close_tutorial": "CLOSE TUTORIAL",
	"tx_inventory": "INVENTORY",
	"tx_evade": "DODGE!",
	"tx_need_key": "YOU NEED THIS LEVEL’S KEY",
	"tx_need_party": "YOU MUST GATHER EVERYONE TO DESCEND",
	"tx_level": "Level",
	"tx_end_turn": "END\nTURN",
	"tx_touch_again":"Touch again to use",

	"popup_win": "[center][color=#f6ff88]VICTORY[/color]\nYou defeated Gorok the troll and cleared his lair of danger.\n\nWe hope you enjoyed it!",
	"popup_lose": "[center][color=#f6ff88]DEFEAT[/color]\nAll your adventurers have fallen. They won't leave this dungeon.\n\nTry again!"
	},
}


func get_help_attr_hint():
	return Lang.get_text("attr_SW")+"\n\n"+Lang.get_text("attr_BT")+"\n\n"+Lang.get_text("attr_HN")+"\n\n"+Lang.get_text("attr_EY")

func get_text(code,vals = []):
	lang = LittleGS.get_current_languaje()
	if !code in texts[lang]: return "<"+code+">"
	else: 
		var tx = texts[lang][code]
		for i in range(vals.size()): tx = tx.replace("#"+str(i+1),str(vals[i]))
		return tx
